manifestVersion: 1
pluginName: EC-NewRest
description: No description
version: 1.0.0
author: Electric Cloud
supportUrl: No support URL
category: Web
coreVersions:
    pluginWizard: 1.0.1
    perl: 1.0.0
configuration:
  shell: ec-perl
  parameters:
   - name: config
     type: entry
     label: Configuration Name
     required: true
     documentation: The name for the created configuration
   - name: endpoint
     label: Endpoint
     type: entry
     required: true
     documentation: Third-party endpoint to connect to.
   - name: credential
     type: credential
     label: Credential
     userNameLabel: Username
     required: true
     passwordLabel: Password
   - name: checkConnection
     label: Check Connection?
     type: checkbox
     checkedValue: true
     uncheckedValue: false
     initiallyChecked: 1
   - name: debugLevel
     label: Debug Level
     type: select
     required: 0
     value: 0
     options:
       - name: Info
         value: 0
       - name: Debug
         value: 1
       - name: Trace
         value: 2

procedures:
- name: Sample Procedure
  description: Sample procedure description
  hasConfig: true # configuration field will be generated automatically
  parameters:
  - name: applicationPath
    documentation: Path to the application
    type: entry
    required: true
    label: Application Path
  - property: check
    documentation: Some checkbox
    checkedValue: true
    uncheckedValue: false
    type: checkbox
    label: Checkbox
  outputParameters:
    deployed: JSON representation of the deployed application
  # Steps are not defined so we assume that this is one-step procedure with a single step named Deploy
  shell: ec-perl
